### ISSUE TITLE
Could not load source '<node_internals>/evalmachine.<anonymous>': Source not found.

### ISSUE THREAD

**Issue by jasoncaunt73** [kevinswiber/newman-debug#1]
I am running using Launch newman (global, prompt)

I am also including an env and global file in the runtime args

```
            "runtimeArgs": [
                "run",
                "${input:postmanCollectionJSON}",
                "--folder",
                "${input:postmanFolder}",
                "--environment",
                "${input:postmanEnvironmentJSON}",
                "--globals",
                "${input:postmanGlobalJSON}",
                "--verbose",
                "--timeout-script",
                "1800000"
            ],
```

But I am getting an error when trying to execute the following line in my collection: 

`let globalFunction = eval(globals.globalFunction)();`

I get the following:

Could not load source '<node_internals>/evalmachine.<anonymous>': Source not found.

'TypeError: eval(...) is not a function\n    at Object.eval (eval at exec (evalmachine.<anonymous>:13483:2548), <anonymous>:5:50)\n    at Uniscope.exec (evalmachine.<anonymous>:13483:2583)\n    at module.exports (evalmachine.<anonymous>:69:538)\n    at Object.<anonymous> (evalmachine.<anonymous>:72:1901)\n    at evalmachine.<anonymous>:16:26\n    at Array.forEach (<anonymous>)\n    at Object.emit (evalmachine.<anonymous>:15:54)\n    at evalmachine.<anonymous>:52:24\n    at evalmachine.<anonymous>:5:21\n    at evalmachine.<anonymous>:6:18'

This runs fine when just in Newman

**Comment by kevinswiber** [comment]
Ope.  Almost 2 years too late.  But perhaps try removing `"<node_internals>/**"` from `skipFiles`.  Feel free to re-open if still an issue.
